image: ubuntu:18.04

stages:
  - vpn_connect

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y python3 python3-pip openconnect iputils-ping procps
  - pip3 install ansible


Connect to Cisco Sandbox:
  stage: vpn_connect
  script:
    - touch $OC_PID
    - echo $VPN_PASS | openconnect -b -v --pid-file=$OC_PID --user=$VPN_USER --passwd-on-stdin devnetsandbox-us-sjc.cisco.com:$VPN_PORT
    - ps -A | grep openconnect
    - cat $OC_PID
    - pkill -e -F $OC_PID
    - ping $CSR1000V_HOST -c 4
    - ansible-playbook test_playbook
    - pkill -e -F $OC_PID

after_script:
  - ps -A | grep openconnect
