image: docker:19.03.1
services:
  - name: docker:19.03.1-dind

stages:
  - try_container
  - build_container
  - get_config

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ANSIBLE_HOST_KEY_CHECKING: "False"

Build container and install Dependencies:
  stage: build_container
  rules:
    - changes:
      - Dockerfile
      - .gitlab-ci.yml
      when: on_success
    - when: never
  before_script:
    - docker info
    - docker login registry.gitlab.com -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build . -t registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY
    - docker run -t -d --rm --name nettest registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY
    - docker commit nettest registry.gitlab.com/$DOCKER_REPOSITORY
  after_script:
    - docker push registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY


Connect to Cisco Sandbox and backup config:
  image: registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY
  stage: get_config
  script:
    - touch inventory
    - echo "CSR1000V ansible_host=${CSR1000V_HOST}" > inventory
    - ansible-playbook test_playbook.yml -i inventory -e "GITLAB_TOKEN=${GITLAB_TOKEN} CSR1000V_HOST=${CSR1000V_HOST} CSR1000V_USER=${CSR1000V_USER} CSR1000V_PASS=${CSR1000V_PASS} CSR1000V_SSH=${CSR1000V_SSH}" -vvv
  artifacts:
    paths:
      - configs

