image: ubuntu:18.04

stages:
  - build

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y anyconnect python3 python3-pip
  - pip install ansible
  - ansible --version



build:
  stage: build
  script:
    - echo Hello World
