image: ubuntu:18.04

stages:
  - connect

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y lib32z1 lib32ncurses5 python3 python3-pip
  - tar xvf anyconnect-linux64-4.7.04056-predeploy-k9.tar.gz
  - cd anyconnect-linux64-4.7.04056/vpn/
  - ./vpn_install.sh
  - alias vpn='/opt/cisco/anyconnect/bin/vpn'
  - pip3 install ansible
  - ansible --version



connect:
  stage: connect
  script:
    - vpn
