image: ubuntu:18.04

stages:
  - vpn_connect
  - ansible

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y python3 python3-pip openconnect ping pkill
  - pip3 install ansible


Connect to Cisco Sandbox:
  stage: vpn_connect
  script:
    - echo $VPN_PASS | openconnect -b -v --user=$VPN_USER --passwd-on-stdin devnetsandbox-us-sjc.cisco.com:$VPN_PORT
    - ping $CSR1000V_HOST -c 4

Use Ansible to get Runn Config:
  stage: ansible
  script:
    - ansible-playbook test_playbook

after_script:
  - pkill -SIGINT openconnect
