image: ubuntu:18.04

stages:
  - gather_dependents
  - get_config
  
variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  
Build container and install Dependencies:
  stage: gather_dependents
  script:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install -y python3 python3-pip openconnect iputils-ping procps
    - pip3 install ansible paramiko
  artifacts:
    paths: "/"


Connect to Cisco Sandbox and backup config:
  stage: get_config
  script:
    - touch inventory
    - echo "CSR1000V ansible_host=${CSR1000V_HOST}" > inventory
    - ansible-playbook test_playbook -i inventory -e "CSR1000V_HOST=${CSR1000V_HOST} CSR1000V_USER=${CSR1000V_USER} CSR1000V_PASS=${CSR1000V_PASS} CSR1000V_SSH=${CSR1000V_SSH}"
