image: docker:19.03.1
services:
  - name: docker:19.03.1-dind

stages:
  - build_container
  - get_config

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ANSIBLE_HOST_KEY_CHECKING: "False"

Build container and install Dependencies:
  stage: build_container
  before_script:
  - docker info
  - docker login registry.gitlab.com -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker run -t -d --name nettest ubuntu:18.04  /bin/bash
    - docker exec -d nettest apt-get update -y
    - docker exec -d nettest apt-get upgrade -y
    - docker exec -d nettest apt-get install -y python3 python3-pip openconnect iputils-ping procps
    - docker exec -d nettest pip3 install ansible paramiko
    - docker commit nettest
  after_script:
    - docker push registry.gitlab.com/"$DOCKER_USERNAME"/"DOCKER_REPOSITORY"

Connect to Cisco Sandbox and backup config:
  image: dsynapalos/net_test
  stage: get_config
  script:
    - touch inventory
    - echo "CSR1000V ansible_host=${CSR1000V_HOST}" > inventory
    - ansible-playbook test_playbook -i inventory -e "CSR1000V_HOST=${CSR1000V_HOST} CSR1000V_USER=${CSR1000V_USER} CSR1000V_PASS=${CSR1000V_PASS} CSR1000V_SSH=${CSR1000V_SSH}"
