image: ubuntu:18.04

stages:
  - vpn_connect

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y python3 python3-pip openconnect iputils-ping procps
  - pip3 install ansible


Connect to Cisco Sandbox:
  stage: vpn_connect
  script:
    - touch oc.pid
    - echo $VPN_PASS | openconnect -b -v --pid-file=oc.pid --user=$VPN_USER --passwd-on-stdin devnetsandbox-us-sjc.cisco.com:$VPN_PORT
    - cat oc.pid
    - ping $CSR1000V_HOST -c 4
    - ansible-playbook test_playbook

after_script:
  - pkill -e -F oc.pid
