image: docker:19.03.1
services:
  - name: docker:19.03.1-dind

stages:
  - try_container
  - build_container
  - get_config

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ANSIBLE_HOST_KEY_CHECKING: "False"

Build container and install Dependencies:
  stage: build_container
  rules:
    - changes:
      - Dockerfile
      - .gitlab-ci.yml
      when: on_success
    - when: never
  before_script:
    - docker info
    - docker login registry.gitlab.com -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build . -t registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY
    - docker run -t -d --rm --name nettest registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY
    - docker commit nettest registry.gitlab.com/$DOCKER_REPOSITORY
  after_script:
    - docker push registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY


Connect to Cisco Sandbox and backup config:
  image: registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY
  stage: get_config
  script:
    - ansible-playbook gather_configs.yml -i inventory -e "DOCKER_USERNAME=${DOCKER_USERNAME} GITLAB_TOKEN=${GITLAB_TOKEN} NXOS_USER=${NXS_USER} NXOS_PASS=${NXOS_PASS} IOS_USER=${IOS_USER} IOS_PASS=${IOS_PASS} CSR1000V_SSH=${CSR1000V_SSH}" -vvvvv
  artifacts:
    paths:
      - configs

