image: ubuntu:18.04

stages:
  - connect

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y python3 python3-pip openconnect
  - pip3 install ansible


connect:
  stage: connect
  script:
    - echo $VPN_PASS | openconnect -b --user=$VPN_USER --passwd-on-stdin --no-cert-check devnetsandbox-us-sjc.cisco.com:$VPN_PORT
