---
- hosts: localhost
  become: yes
  gather_facts: no
  
  vars:
    - config_folder: /tmp/configs
  
  tasks:    
    - debug: msg={{ hostvars[item].inventory_dict }}
      with_items: groups['ALL_OS']
      
    - name: Add configs
      shell: "git add ."
      args:
        chdir: "{{ config_folder }}"
      register: gitadd
      
    - name: check differences
      shell: git diff HEAD
      args:
        chdir: "{{ config_folder }}"
      register: diffs

    - name: get time
      shell: TZ=Europe/Athens date '+%Y-%m-%d %H:%M:%S'
      register: timestamp
      when: diffs.stdout

    - name: Git commit
      shell: git commit -m "Ansible Managed Backup - {{ timestamp.stdout }}"
      args:
        chdir: "{{ config_folder }}"
      register: gitcommit
      when: diffs.stdout

    - name: Git push
      shell: git push origin master
      args:
        chdir: "{{ config_folder }}"
      when: diffs.stdout
      register: gitpush