---
- hosts: CSR1000V
  become: yes
  become_method: enable
  connection: network_cli

  vars:
    - become_pass: "{{ CSR1000V_PASS }}"
    - ansible_user: "{{ CSR1000V_USER }}"
    - ansible_password: "{{ CSR1000V_PASS }}"
    - ansible_network_os: ios
    - ansible_ssh_port: "{{ CSR1000V_SSH }}"
  
  tasks:
    
    - name: Gather all legacy facts
      ios_facts:
        gather_subset: all
      register: facts
      
    - debug: var=facts
    
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show runn
      register: config
        
    - debug: var=config.stdout_lines
    
    - name: clone GitLab Project
      git:
        repo: "https://dsynapalos:{{ GITLAB_TOKEN | urlencode }}gitlab.com/dsynapalos/configs_inv.git"
        dest: /tmp/configs
    
    - name: configurable backup path
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_net_hostname }}"
          dir_path: /tmp/configs/{{ ansible_net_model }}
          
    - name: commit conf
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_net_hostname }}"
          dir_path: /tmp/configs/{{ ansible_net_model }}
      
    - name: clone GitLab Project
      gitlab_project:
        api_url: https://gitlab.com/dsynapalos
        api_token: "{{ GITLAB_TOKEN }}"
        validate_certs: False
        name: configs_inv
        state: present  
      
    #- copy: content="{{ config.stdout_lines }}" dest=tempfile
    #- name: Validate the sudoers file before saving
    #  lineinfile:
    #    path: tempfile
    #    state: present
    #    line: "{{ item }}"
    #    create: yes
    #  with_items:
    #    "{{config.stdout_lines[0]}}"